### ISSUE TITLE
habitica.py crashes with KeyError: 'specialClass' not in gearStats

### ISSUE THREAD

**Issue by kbavishi** [rbavishi/Habitican-Curse#2]
Here's the backtrace:

``` bash
karanbavishi:Habitican-Curse karan$ python habitica.py
Traceback (most recent call last):
  File "habitica.py", line 53, in <module>
    curses.wrapper(main)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "habitica.py", line 50, in main
    G.intf.Input()
  File "/Users/karan/Habitican-Curse/interface.py", line 278, in Input
    self.Command(command)
  File "/Users/karan/Habitican-Curse/interface.py", line 240, in Command
    CT.GetData()
  File "/Users/karan/Habitican-Curse/content.py", line 149, in GetData
    userStats = H.GetUserStats(data)
  File "/Users/karan/Habitican-Curse/helper.py", line 265, in GetUserStats
    (gearStats['klass'] == "special" and gearStats['specialClass'] == userClass)):
KeyError: 'specialClass'
```

**Comment by rbavishi** [comment]
It has been fixed in the "Fixed special equipment error" commit. Pull the latest code
